services:
  redis:
    image: "redis/redis-stack:7.2.0-v10"
    restart: always
    ports:
      - ${REDIS_PORT:-6379}:6379
      - ${REDIS_INSIGHT_PORT:-8001}:8001
    volumes:
      - redis:/data
volumes:
  redis:
