name: Release gem

on:
  workflow_dispatch:
    inputs:
      rubygems-otp-code:
        description: RubyGems OTP code
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version:
          - 3.3
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler: latest
          bundler-cache: true
      - name: Configure Git
        # Configure Git to push a tag
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
      - name: Release gem
        run: bundle exec rake release
        env:
          GEM_HOST_API_KEY: ${{ secrets.GEM_HOST_API_KEY }}
          GEM_HOST_OTP_CODE: ${{ inputs.rubygems-otp-code }}
